version: '3.9'

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
#
#  app:
#    image: pismo-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: pismo-app
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
#      SPRING_DATASOURCE_USERNAME: test
#      SPRING_DATASOURCE_PASSWORD: test
